[package]
name = "day1"
version = "0.1.0"
authors = ["Julien Duponchelle <julien@duponchelle.info>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
